// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: IUpdateService.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Updater.GRPCService.Protocol {
  public static partial class IUpdateService
  {
    static readonly string __ServiceName = "Updater.gRPCService.Protocol.IUpdateService";

    static readonly grpc::Marshaller<global::Updater.GRPCService.Protocol.RpcRequest> __Marshaller_Updater_gRPCService_Protocol_RpcRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Updater.GRPCService.Protocol.RpcRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Updater.GRPCService.Protocol.RpcResponse> __Marshaller_Updater_gRPCService_Protocol_RpcResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Updater.GRPCService.Protocol.RpcResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Updater.GRPCService.Protocol.RpcRequest, global::Updater.GRPCService.Protocol.RpcResponse> __Method_GetResponse = new grpc::Method<global::Updater.GRPCService.Protocol.RpcRequest, global::Updater.GRPCService.Protocol.RpcResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetResponse",
        __Marshaller_Updater_gRPCService_Protocol_RpcRequest,
        __Marshaller_Updater_gRPCService_Protocol_RpcResponse);

    static readonly grpc::Method<global::Updater.GRPCService.Protocol.RpcRequest, global::Updater.GRPCService.Protocol.RpcResponse> __Method_GetResponseStream = new grpc::Method<global::Updater.GRPCService.Protocol.RpcRequest, global::Updater.GRPCService.Protocol.RpcResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "GetResponseStream",
        __Marshaller_Updater_gRPCService_Protocol_RpcRequest,
        __Marshaller_Updater_gRPCService_Protocol_RpcResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Updater.GRPCService.Protocol.IUpdateServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of IUpdateService</summary>
    [grpc::BindServiceMethod(typeof(IUpdateService), "BindService")]
    public abstract partial class IUpdateServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Updater.GRPCService.Protocol.RpcResponse> GetResponse(global::Updater.GRPCService.Protocol.RpcRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task GetResponseStream(global::Updater.GRPCService.Protocol.RpcRequest request, grpc::IServerStreamWriter<global::Updater.GRPCService.Protocol.RpcResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for IUpdateService</summary>
    public partial class IUpdateServiceClient : grpc::ClientBase<IUpdateServiceClient>
    {
      /// <summary>Creates a new client for IUpdateService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public IUpdateServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for IUpdateService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public IUpdateServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected IUpdateServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected IUpdateServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Updater.GRPCService.Protocol.RpcResponse GetResponse(global::Updater.GRPCService.Protocol.RpcRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetResponse(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Updater.GRPCService.Protocol.RpcResponse GetResponse(global::Updater.GRPCService.Protocol.RpcRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetResponse, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Updater.GRPCService.Protocol.RpcResponse> GetResponseAsync(global::Updater.GRPCService.Protocol.RpcRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetResponseAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Updater.GRPCService.Protocol.RpcResponse> GetResponseAsync(global::Updater.GRPCService.Protocol.RpcRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetResponse, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::Updater.GRPCService.Protocol.RpcResponse> GetResponseStream(global::Updater.GRPCService.Protocol.RpcRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetResponseStream(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Updater.GRPCService.Protocol.RpcResponse> GetResponseStream(global::Updater.GRPCService.Protocol.RpcRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_GetResponseStream, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override IUpdateServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new IUpdateServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(IUpdateServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetResponse, serviceImpl.GetResponse)
          .AddMethod(__Method_GetResponseStream, serviceImpl.GetResponseStream).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, IUpdateServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetResponse, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Updater.GRPCService.Protocol.RpcRequest, global::Updater.GRPCService.Protocol.RpcResponse>(serviceImpl.GetResponse));
      serviceBinder.AddMethod(__Method_GetResponseStream, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Updater.GRPCService.Protocol.RpcRequest, global::Updater.GRPCService.Protocol.RpcResponse>(serviceImpl.GetResponseStream));
    }

  }
}
#endregion
